name: pirate_badge
version: 0.0.0
description: 
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  browser: ^0.10.0+2
  angular2: ^2.0.0-beta.0
transformers:
- angular2:
    entry_points: web/main.dart